### 
### 27048 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZiZjIzOTRmY2IwMmIxYWNkZTJkZWUiLCJpYXQiOjE3MDE1NzMyNTMsImV4cCI6MTcwMTY1OTY1M30.CKXyiwiiApB3c8FbdxzXdtPDPv0L87OVJC_BLYJthec

### 2704 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZiZjI0MjRmY2IwMmIxYWNkZTJkZjMiLCJpYXQiOjE3MDE1NzMyNzMsImV4cCI6MTcwMTY1OTY3M30.eusJ7SgOEH5tcmdcM2YL72iQN5CHdfRtUnsCgyO-7PA




POST http://localhost:8800/post/create-post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZiZjI0MjRmY2IwMmIxYWNkZTJkZjMiLCJpYXQiOjE3MDE2NzYxMjAsImV4cCI6MTcwNTkwOTcyMH0.0QeAsrqqysCf7IFQTV6NidCiOwdtjOnJ78vLkJ_33YY
Content-Type: application/json

{
    "description": "This is the descript"
}

###

POST http://localhost:8800/post/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZiZjI0MjRmY2IwMmIxYWNkZTJkZjMiLCJpYXQiOjE3MDE2NzYxMjAsImV4cCI6MTcwNTkwOTcyMH0.0QeAsrqqysCf7IFQTV6NidCiOwdtjOnJ78vLkJ_33YY
Content-Type: application/json


###


POST http://localhost:8800/post/656bfa254d852bb6879e7028
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZiZjI0MjRmY2IwMmIxYWNkZTJkZjMiLCJpYXQiOjE3MDE2NzYxMjAsImV4cCI6MTcwNTkwOTcyMH0.0QeAsrqqysCf7IFQTV6NidCiOwdtjOnJ78vLkJ_33YY
Content-Type: application/json


###

POST http://localhost:8800/post/get-user-post/656bf2394fcb02b1acde2dee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZiZjI0MjRmY2IwMmIxYWNkZTJkZjMiLCJpYXQiOjE3MDE2NzYxMjAsImV4cCI6MTcwNTkwOTcyMH0.0QeAsrqqysCf7IFQTV6NidCiOwdtjOnJ78vLkJ_33YY
Content-Type: application/json
###


