
###  RESET PASSWORD EMAIL 
###WORKING FINE
POST http://localhost:8800/users/request-resetpassword
content-type: application/json

{
    "email": "sulemanahmed2704@gmail.com"
}

### Reset Password // and redirect to specific page
###WORKING FINE

POST http://localhost:8800/users/password-reset
Content-Type: application/json

{
    "userId": "656bf2424fcb02b1acde2df3", 
    "password" : "5047"
}