# # GET_USER
POST http://localhost:8800/users/get-user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc0NzlkZGI3ZjEzYzNhNDQyZWEyZWUiLCJpYXQiOjE3MDIxOTE5MDQsImV4cCI6MTcwNjQyNTUwNH0.JlUB8DOO2xzXaXiKEcmyaMSFtFPdljbahOndicWNo7U

# ###
# # UPDATE_USER

PUT  http://localhost:8800/users/update-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc0NzlkZGI3ZjEzYzNhNDQyZWEyZWUiLCJpYXQiOjE3MDIxOTE5MDQsImV4cCI6MTcwNjQyNTUwNH0.JlUB8DOO2xzXaXiKEcmyaMSFtFPdljbahOndicWNo7U
Content-Type: application/json

{
     "firstName": "Suleman 2704 UPdated",
     "lastName": "Ahmed",
     "location": "Pakistan",
     "profileUrl": "alpha",
     "profession": "Student"
}


# ###
# #PROFILE_VIEW
# POST http://localhost:8800/users/profile-view
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc0NzlkZGI3ZjEzYzNhNDQyZWEyZWUiLCJpYXQiOjE3MDIxOTE5MDQsImV4cCI6MTcwNjQyNTUwNH0.JlUB8DOO2xzXaXiKEcmyaMSFtFPdljbahOndicWNo7U
# Content-Type: application/json 

# {
#     "id": "65753101a0bb348055fbf218"
# }

# ###

# POST http://localhost:8800/users/friend-request
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc0NzlkZGI3ZjEzYzNhNDQyZWEyZWUiLCJpYXQiOjE3MDIxOTE5MDQsImV4cCI6MTcwNjQyNTUwNH0.JlUB8DOO2xzXaXiKEcmyaMSFtFPdljbahOndicWNo7U
# Content-Type: application/json

# {
#     "requestTo": "657479ddb7f13c3a442ea2ee"
# }

# ### WORKING FINE SOME PROBLEM WHILE FETCHING DATA FROM ANOTHER SCHEMA TO ANOTHER ONE 
 
#  POST http://localhost:8800/users/get-friend-request
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc0NzlkZGI3ZjEzYzNhNDQyZWEyZWUiLCJpYXQiOjE3MDIxOTE5MDQsImV4cCI6MTcwNjQyNTUwNH0.JlUB8DOO2xzXaXiKEcmyaMSFtFPdljbahOndicWNo7U
# Content-Type: application/json



 
# ###
 
# POST http://localhost:8800/users/accept-request
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc0NzlkZGI3ZjEzYzNhNDQyZWEyZWUiLCJpYXQiOjE3MDIxOTE5MDQsImV4cCI6MTcwNjQyNTUwNH0.JlUB8DOO2xzXaXiKEcmyaMSFtFPdljbahOndicWNo7U
# Content-Type: application/json

# {
#     "rid": "65757e558767679d7f44fe3f",
#     "status": "Accepted"
# }



#  ###

# # POST http://localhost:8800/users/-request
# # Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc0NzlkZGI3ZjEzYzNhNDQyZWEyZWUiLCJpYXQiOjE3MDIxOTE5MDQsImV4cCI6MTcwNjQyNTUwNH0.JlUB8DOO2xzXaXiKEcmyaMSFtFPdljbahOndicWNo7U
# # Content-Type: application/json

# # {
# #     "rid": "65757e558767679d7f44fe3f",
# #     "status": "Accepted"
# # }

#  ###

POST http://localhost:8800/users/suggested-friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTc0NzlkZGI3ZjEzYzNhNDQyZWEyZWUiLCJpYXQiOjE3MDIyMTE5MzEsImV4cCI6MTcwNjQ0NTUzMX0.Nhbohup50Q2zxF-H6_2IWMcpNvLlUSgRoHdDGbHl6HY
Content-Type: application/json


{}

 ###
 ### SULEMAN 2704 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZhY2Q2Yzk3MDM4Y2RlYzZmYjk5M2QiLCJpYXQiOjE3MDE0OTg2MTQsImV4cCI6MTcwMTU4NTAxNH0.w8Z0mIyLl5hO_2FBCUjGgX3uorgfJUXdDdukLFA_Zxs